---

#- hosts: controller1
#  become: true
#  become_user: root
#  vars_files:
#    - group_vars/all
#  roles:
#    - controller1_setup

#- hosts: controller2
#  become: true
#  become_user: root
#  vars_files:
#    - group_vars/all
#  roles:
#    - controller2_setup

#- hosts: controller3
#  become: true
#  become_user: root
#  vars_files:
#    - group_vars/all
#  roles:
#    - controller3_setup


#- hosts: controller
#  become: true
#  become_user: root
#  vars_files:
#    - group_vars/all

#  tasks:
#   - name: create file
#     shell: pcs status 
#     register: wrt_file
#     tags: 
#       - test
#   - debug: var=wrt_file.stdout_lines 

- hosts: localhost
  tasks:
    - name: file find
      find: paths="/var/lib/jenkins" recurse=yes patterns="ansible_haproxy*"
      register: find_file
    - debug: var=find_file.stdout_lines
